image: node:8.11.3
pages:
  cache:
    paths:
    - node_modules/
  script:
  - git config --global user.name "WitherZuo"
  - git config --global user.email "openworld189@gmail.com"
  - npm install hexo-cli -g
  - npm install
  - hexo clean
  - hexo g
  - cd public/
  - curl -H 'Content-Type:text/plain' --data-binary @urls.txt "http://data.zz.baidu.com/urls?site=https://www.wzblog.fun&token=TwFhN5gM4BMIe0a9" 
  artifacts:
    paths:
    - public
  only:
  - master