image: node:8.11.3
pages:
  cache:
    paths:
    - node_modules/
  script:
  - git config --global user.name "WitherZuo"
  - git config --global user.email "openworld189@gmail.com"
  - npm install hexo-cli -g
  - hexo clean
  - npm install
  - hexo g
  artifacts:
    paths:
    - public
  only:
  - master