<link rel="manifest" href="/manifest.json">
<link rel="apple-touch-icon" href="https://www.wzblog.fun/images/apple-touch-icon-next.png">
<meta name="apple-mobile-web-app-title" content="WzBlog">
<meta name="apple-mobile-web-app-capable" content="yes">
<script defer="defer" src="https://cdn.jsdelivr.net/npm/instant.page@3.0.0/instantpage.min.js" type="module"></script>
<link rel="preconnect" href="https://hm.baidu.com/">
<link rel="preconnect" href="http://push.zhanzhang.baidu.com/">
<link rel="preconnect" href="http://api.share.baidu.com/">
<link rel="preconnect" href="https://zz.bdstatic.com/">
<link rel="preconnect" href="https://sp0.baidu.com/">